apiVersion: v1
kind: Pod
metadata:
  name: gpu-realesrgan-upscale
spec:
  restartPolicy: Never
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: persistent-volume
  terminationGracePeriodSeconds: 1
  containers:
    - name: gpu-worker
      image: sgs-registry.snucse.org/ws-7l3atgjy3al41/svfr-base:latest
      env:
        - name: HOME
          value: /data
        - name: PATH
          value: /data/python/bin:/data/realesrgan-venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
      command:
        - /bin/bash
        - -c
        - |
          # Activate Real-ESRGAN virtual environment
          source /data/realesrgan-venv/bin/activate

          # Configuration
          INPUT_VIDEO="/data/input/before.mp4"
          OUTPUT_VIDEO="/data/output/after_upscaled_4x.mp4"
          FRAMES_DIR="/data/output/frames"
          UPSCALED_DIR="/data/output/frames_upscaled"

          # Clean up previous runs
          rm -rf ${FRAMES_DIR} ${UPSCALED_DIR}
          mkdir -p ${FRAMES_DIR} ${UPSCALED_DIR}

          # Step 1: Extract frames from video
          echo "Step 1: Extracting frames from video..."
          ffmpeg -i ${INPUT_VIDEO} ${FRAMES_DIR}/frame_%04d.png
          FRAME_COUNT=$(ls ${FRAMES_DIR}/*.png | wc -l)
          echo "Extracted ${FRAME_COUNT} frames"

          # Step 2: Upscale frames with Real-ESRGAN (official script)
          echo "Step 2: Upscaling ${FRAME_COUNT} frames with Real-ESRGAN (4x)..."
          cd /data/Real-ESRGAN
          python inference_realesrgan.py \
            -n RealESRGAN_x4plus \
            -i ${FRAMES_DIR} \
            -o ${UPSCALED_DIR} \
            -s 4 \
            --suffix '' \
            --fp32

          # Verify upscaled frames
          UPSCALED_COUNT=$(ls ${UPSCALED_DIR}/*.png | wc -l)
          echo "Upscaled ${UPSCALED_COUNT} frames"

          # Step 3: Reassemble video from upscaled frames (optimized encoding)
          echo "Step 3: Reassembling video from upscaled frames..."
          # Quality-optimized H.264 encoding:
          #   -crf 18: High quality (lower = better, 18 is visually lossless)
          #   -preset slower: Better compression efficiency (~10% quality gain)
          #   -profile:v high: Advanced H.264 features for better quality
          ffmpeg -framerate 24 -i ${UPSCALED_DIR}/frame_%04d.png \
            -i ${INPUT_VIDEO} \
            -map 0:v -map 1:a? \
            -c:v libx264 -crf 18 -preset slower -profile:v high \
            -c:a copy \
            -pix_fmt yuv420p \
            ${OUTPUT_VIDEO}

          # Get output video info
          echo "✅ Video upscaling complete!"
          ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of default=noprint_wrappers=1 ${OUTPUT_VIDEO}

          echo "Done!"
      resources:
        limits:
          nvidia.com/gpu: 1
      volumeMounts:
        - name: my-volume
          mountPath: /data
